services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Lemonmind\ObjectUpdateLoggerBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']